---
platform: linux

inputs:
- name: concourse-terraform
- name: terraform-source-dir

params:
  TF_WORKING_DIR:
  TF_DIR_PATH:
  ERROR_ON_NO_CHANGES:
  DEBUG:

run:
  path: concourse-terraform/bin/concourse-terraform
  args:
  - plan
