resources:

# source code
# ===========
- name: concourse-terraform
  type: git
  source:
    uri: https://github.com/Snapkitchen/concourse-terraform.git

# docker image
# ============
- name: concourse-terraform-image
  type: docker-image
  source:
    repository: snapkitchen/concourse-terraform
    tag: 0.11.10

jobs:
- name: terraform-plan
  plan:
  - get: concourse-terraform
  - get: concourse-terraform-image
  - task: terraform-plan
    image: concourse-terraform-image
    input_mapping:
      terraform-source-dir: concourse-terraform
    config:
      platform: linux
      inputs:
      - name: concourse-terraform
      - name: terraform-source-dir
      params:
        TF_WORKING_DIR: terraform-source-dir
        TF_DIR_PATH:
        ERROR_ON_NO_CHANGES: false
        DEBUG: 1
      run:
        path: /bin/sh
        args:
        - -c
        - |
          export PYTHONPATH="$(pwd)/concourse-terraform:${PYTHONPATH}"
          concourse-terraform/bin/concourse-terraform plan
